export const TICKET_REQUEST = 'TICKET_REQUEST'
export const TICKET_SUCCESS = 'TICKET_SUCCESS'
export const TICKET_FAIL = 'TICKET_FAIL'
export const TICKET_RESET = 'TICKET_RESET'

export const TICKET_REQUEST_DELETE = 'TICKET_REQUEST_DELETE'
export const TICKET_SUCCESS_DELETE = 'TICKET_SUCCESS_DELETE'
export const TICKET_FAIL_DELETE = 'TICKET_FAIL_DELETE'
export const TICKET_RESET_DELETE = 'TICKET_RESET_DELETE'

export const TICKET_REQUEST_USED = 'TICKET_REQUEST_USED'
export const TICKET_SUCCESS_USED = 'TICKET_SUCCESS_USED'
export const TICKET_FAIL_USED = 'TICKET_FAIL_USED'
export const TICKET_RESET_USED = 'TICKET_RESET_USED'

export const TICKET_SCANNED_REQUEST = 'TICKET_SCANNED_REQUEST'
export const TICKET_SCANNED_SUCCESS = 'TICKET_SCANNED_SUCCESS'
export const TICKET_SCANNED_FAIL = 'TICKET_SCANNED_FAIL'
export const TICKET_SCANNED_RESET = 'TICKET_SCANNED_RESET'