export const HELP_LIST_REQUEST = 'HELP_LIST_REQUEST'
export const HELP_LIST_SUCCESS = 'HELP_LIST_SUCCESS'
export const HELP_LIST_FAIL = 'HELP_LIST_FAIL'
export const HELP_LIST_RESET = 'HELP_LIST_RESET'

export const HELP_DELETE_REQUEST = 'HELP_DELETE_REQUEST'
export const HELP_DELETE_SUCCESS = 'HELP_DELETE_SUCCESS'
export const HELP_DELETE_FAIL = 'HELP_DELETE_FAIL'

export const HELP_DETAIL_REQUEST = 'HELP_DETAIL_REQUEST'
export const HELP_DETAIL_SUCCESS = 'HELP_DETAIL_SUCCESS'
export const HELP_DETAIL_FAIL = 'HELP_DETAIL_FAIL'
export const HELP_DETAIL_RESET = 'HELP_DETAIL_RESET'

export const HELP_SAVE_REQUEST = 'HELP_SAVE_REQUEST'
export const HELP_SAVE_SUCCESS = 'HELP_SAVE_SUCCESS'
export const HELP_SAVE_FAIL = 'HELP_SAVE_FAIL'
export const HELP_SAVE_RESET = 'HELP_SAVE_RESET'

export const HELP_SEND_RESPONSE_REQUEST = 'HELP_SEND_RESPONSE_REQUEST'
export const HELP_SEND_RESPONSE_SUCCESS = 'HELP_SEND_RESPONSE_SUCCESS'
export const HELP_SEND_RESPONSE_FAIL = 'HELP_SEND_RESPONSE_FAIL'
export const HELP_SEND_RESPONSE_RESET = 'HELP_SEND_RESPONSE_RESET'