export const PAYMENT_LIST_REQUEST = 'PAYMENT_LIST_REQUEST'
export const PAYMENT_LIST_SUCCESS = 'PAYMENT_LIST_SUCCESS'
export const PAYMENT_LIST_FAIL = 'PAYMENT_LIST_FAIL'
export const PAYMENT_LIST_RESET = 'PAYMENT_LIST_RESET'

export const SERVICE_LIST_DATAGENERATION_REQUEST = 'SERVICE_LIST_DATAGENERATION_REQUEST'
export const SERVICE_LIST_DATAGENERATION_SUCCESS = 'SERVICE_LIST_DATAGENERATION_SUCCESS'
export const SERVICE_LIST_DATAGENERATION_FAIL = 'SERVICE_LIST_DATAGENERATION_FAIL'
export const SERVICE_LIST_DATAGENERATION_RESET = 'SERVICE_LIST_DATAGENERATION_RESET'