export const SERVICE_LIST_REQUEST = 'SERVICE_LIST_REQUEST'
export const SERVICE_LIST_SUCCESS = 'SERVICE_LIST_SUCCESS'
export const SERVICE_LIST_FAIL = 'SERVICE_LIST_FAIL'
export const SERVICE_LIST_RESET = 'SERVICE_LIST_RESET'

export const SERVICE_DETAIL_REQUEST = 'SERVICE_DETAIL_REQUEST'
export const SERVICE_DETAIL_SUCCESS = 'SERVICE_DETAIL_SUCCESS'
export const SERVICE_DETAIL_FAIL = 'SERVICE_DETAIL_FAIL'
export const SERVICE_DETAIL_RESET = 'SERVICE_DETAIL_RESET'

export const SERVICE_DELETE_REQUEST = 'SERVICE_DELETE_REQUEST'
export const SERVICE_DELETE_SUCCESS = 'SERVICE_DELETE_SUCCESS'
export const SERVICE_DELETE_FAIL = 'SERVICE_DELETE_FAIL'