export const ROUTE_REQUEST = 'RETRIEVING_ROUTE'
export const ROUTE_SUCCESS = 'RETRIEVING_ROUTE_SUCCESS'
export const ROUTE_FAIL = 'RETRIEVING_ROUTE_FAILURE'

export const STORING_LOOKUP_DATA = 'STORING_LOOKUP_DATA'
export const RETRIEVING_LOOKUP_DATA = 'RETRIEVING_LOOKUP_DATA'

export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL'

export const USER_LOGOUT = 'USER_LOGOUT'

export const USER_DETAIL_REQUEST = 'USER_DETAIL_REQUEST'
export const USER_DETAIL_SUCCESS = 'USER_DETAIL_SUCCESS'
export const USER_DETAIL_FAIL = 'USER_DETAIL_FAIL'
export const USER_DETAIL_RESET = 'USER_DETAIL_RESET'

export const USER_LIST_REQUEST = 'USER_LIST_REQUEST'
export const USER_LIST_SUCCESS = 'USER_LIST_SUCCESS'
export const USER_LIST_FAIL = 'USER_LIST_FAIL'
export const USER_LIST_RESET = 'USER_LIST_RESET'

export const HELP_LIST_REQUEST = 'HELP_LIST_REQUEST'
export const HELP_LIST_SUCCESS = 'HELP_LIST_SUCCESS'
export const HELP_LIST_FAIL = 'HELP_LIST_FAIL'
export const HELP_LIST_RESET = 'HELP_LIST_RESET'