export const ROUTE_REQUEST = 'RETRIEVING_ROUTE'
export const ROUTE_SUCCESS = 'RETRIEVING_ROUTE_SUCCESS'
export const ROUTE_FAIL = 'RETRIEVING_ROUTE_FAILURE'
export const ROUTE_RESET = 'RETRIEVING_ROUTE_RESET'

export const ROUTE_ALL_REQUEST = 'ROUTE_ALL_REQUEST'
export const ROUTE_ALL_SUCCESS = 'ROUTE_ALL_SUCCESS'
export const ROUTE_ALL_FAIL = 'ROUTE_ALL_FAIL'

export const LOOKUP_DATA_MANAGEMENT = 'LOOKUP_DATA_MANAGEMENT'

export const USER_REGISTER = 'USER_REGISTER'
export const USER_REGISTER_PROCESS = 'USER_REGISTER_PROCESS'
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL'
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS'
export const USER_REGISTER_RESET = 'USER_REGISTER_RESET'

export const USER_PASSWORD_CHANGE_PROCESSING = 'USER_REGISTER_RESET'
export const USER_PASSWORD_CHANGE_SUCCESS = 'USER_PASSWORD_CHANGE_SUCCESS'
export const USER_PASSWORD_CHANGE_FAILURE = 'USER_PASSWORD_CHANGE_FAILURE'
export const USER_PASSWORD_CHANGE_RESET = 'USER_PASSWORD_CHANGE_RESET'

export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL'

export const USER_LOGOUT = 'USER_LOGOUT'

export const STORE_DATE = 'STORE_DATE'

export const VENDOR_LIST_REQUEST = 'VENDOR_LIST_REQUEST'
export const VENDOR_LIST_SUCCESS = 'VENDOR_LIST_SUCCESS'
export const VENDOR_LIST_FAIL = 'VENDOR_LIST_FAIL'

export const USER_DETAIL_REQUEST = 'USER_DETAIL_REQUEST'
export const USER_DETAIL_SUCCESS = 'USER_DETAIL_SUCCESS'
export const USER_DETAIL_FAIL = 'USER_DETAIL_FAIL'
export const USER_DETAIL_RESET = 'USER_DETAIL_RESET'

export const CUSTOMER_DETAILS_REQUEST = 'CUSTOMER_DETAILS_REQUEST'
export const CUSTOMER_DETAILS_SUCCESS = 'CUSTOMER_DETAILS_SUCCESS'
export const CUSTOMER_DETAILS_FAILURE = 'CUSTOMER_DETAILS_FAILURE'
export const CUSTOMER_DETAILS_RESET = 'CUSTOMER_DETAILS_RESET'

export const CUSTOMER_EDIT_REQUEST = 'CUSTOMER_EDIT_REQUEST'
export const CUSTOMER_EDIT_SUCCESS = 'CUSTOMER_EDIT_SUCCESS'
export const CUSTOMER_EDIT_FAILURE = 'CUSTOMER_EDIT_FAILURE'
export const CUSTOMER_EDIT_RESET = 'CUSTOMER_EDIT_RESET'

export const USER_CUSTOMER_UPDATE_RESET = 'USER_CUSTOMER_UPDATE_RESET'

export const USER_UPDATE_RESET = 'USER_UPDATE_RESET'
export const USER_UPDATE_REQUEST = 'USER_UPDATE_REQUEST'
export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS'
export const USER_UPDATE_FAIL = 'USER_UPDATE_FAIL'

export const SEAT_LIST_SUCCESS = 'SEAT_LIST_SUCCESS'
export const SEAT_LIST_REQUEST = 'SEAT_LIST_REQUEST'
export const SEAT_LIST_FAIL = 'SEAT_LIST_FAIL'

export const USER_LIST_REQUEST = 'USER_LIST_REQUEST'
export const USER_LIST_SUCCESS = 'USER_LIST_SUCCESS'
export const USER_LIST_FAIL = 'USER_LIST_FAIL'
export const USER_LIST_RESET = 'USER_LIST_RESET'

export const HELP_LIST_REQUEST = 'HELP_LIST_REQUEST'
export const HELP_LIST_CREATE = 'HELP_LIST_CREATE'
export const HELP_LIST_SUCCESS = 'HELP_LIST_SUCCESS'
export const HELP_LIST_FAIL = 'HELP_LIST_FAIL'
export const HELP_LIST_RESET = 'HELP_LIST_RESET'

export const HELP_RESPONSE_REQUEST = 'HELP_RESPONSE_REQUEST'
export const HELP_RESPONSE_SUCCESS = 'HELP_RESPONSE_SUCCESS'
export const HELP_RESPONSE_FAIL = 'HELP_RESPONSE_FAIL'
export const HELP_RESPONSE_RESET = 'HELP_RESPONSE_FAIL'

export const LOCATION_LIST_REQUEST = 'LOCATION_LIST_REQUEST'
export const LOCATION_LIST_SUCCESS = 'LOCATION_LIST_SUCCESS'
export const LOCATION_LIST_FAIL = 'LOCATION_LIST_FAIL'
export const LOCATION_LIST_RESET = 'LOCATION_LIST_RESET'

export const SEARCH_LOCATION_REQUEST = 'SEARCH_LOCATION_REQUEST'
export const SEARCH_LOCATION_SUCCESS = 'SEARCH_LOCATION_SUCCESS'
export const SEARCH_LOCATION_FAIL = 'SEARCH_LOCATION_FAIL'
export const SEARCH_LOCATION_RESET = 'SEARCH_LOCATION_RESET'

export const CART_ADD_REQUEST = 'CART_ADD_REQUEST'
export const CART_ADD_SUCCESS = 'CART_ADD_SUCCESS'
export const CART_ADD_FAIL = 'CART_ADD_FAIL'
export const CART_ADD_RESET = 'CART_ADD_RESET'

export const CART_DISPATCH_REQUEST = 'CART_DISPATCH_REQUEST'
export const CART_DISPATCH_SUCCESS = 'CART_DISPATCH_FAILURE'
export const CART_DISPATCH_UNCHANGED = 'CART_DISPATCH_UNCHANGED'
export const CART_DISPATCH_RESET = 'CART_DISPATCH_RESET'
export const CART_DISPATCH_FAILURE = 'CART_DISPATCH_FAILURE'

export const CART_VIEW_REQUEST = 'CART_VIEW_REQUEST'
export const CART_VIEW_SUCCESS = 'CART_VIEW_SUCCESS'
export const CART_VIEW_FAIL = 'CART_VIEW_FAIL'
export const CART_VIEW_RESET = 'CART_VIEW_RESET'

export const CART_CHECK_SUCCESS = 'CART_CHECK_SUCCESS'

export const ACCESS_PRICING_INFO = 'ACCESS_PRICING_INFO' 
export const FAILURE_PRICING_INFO = 'FAILURE_PRICING_INFO' 

export const FILTER_ROUTE_REQUEST = 'FILTER_ROUTE_REQUEST'
export const FILTER_ROUTE_SUCCESS = 'FILTER_ROUTE_SUCCESS'
export const FILTER_ROUTE_FAIL = 'FILTER_ROUTE_FAIL'
export const FILTER_ROUTE_RESET = 'FILTER_ROUTE_RESET'

export const PROCESSING_PAYMENT_APPROVAL = 'PROCESSING_PAYMENT_APPROVAL'
export const PROCESSED_PAYMENT_APPROVAL = 'PROCESSED_PAYMENT_APPROVAL'
export const FAILURE_PAYMENT_APPROVAL = 'FAILURE_PAYMENT_APPROVAL'

export const DELETING_CART_ITEM = 'DELETING_CART_ITEM'
export const DELETED_CART_ITEM = 'DELETED_CART_ITEM'
export const UNSUCCESSFUL_DELETE_CART_ITEM = 'UNSUCCESSFUL_DELETE_CART_ITEM'
export const DELETE_CART_RESET = 'DELETE_CART_RESET'

export const TICKET_LIST_REQUEST = 'TICKET_LIST_REQUEST'
export const TICKET_LIST_SUCCESS = 'TICKET_LIST_SUCCESS'
export const TICKET_LIST_FAILURE = 'TICKET_LIST_FAILURE'
export const TICKET_LIST_RESET = 'TICKET_LIST_RESET'

export const VERIFY_USER_REQUEST = 'VERIFY_USER_REQUEST'
export const VERIFY_USER_SUCCESS = 'VERIFY_USER_SUCCESS'
export const VERIFY_USER_FAIL = 'VERIFY_USER_FAIL'
export const VERIFY_USER_RESET = 'VERIFY_USER_RESET'

export const RESET_USER_REQUEST = 'RESET_USER_REQUEST'
export const RESET_USER_SUCCESS = 'RESET_USER_SUCCESS'
export const RESET_USER_FAIL = 'RESET_USER_FAIL'
export const RESET_USER_RESET = 'RESET_USER_RESET'