export const ROUTE_REQUEST = 'RETRIEVING_ROUTE'
export const ROUTE_SUCCESS = 'RETRIEVING_ROUTE_SUCCESS'
export const ROUTE_FAIL = 'RETRIEVING_ROUTE_FAILURE'

export const LOOKUP_DATA_MANAGEMENT = 'LOOKUP_DATA_MANAGEMENT'

export const USER_REGISTER = 'USER_REGISTER'
export const USER_REGISTER_PROCESS = 'USER_REGISTER_PROCESS'
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL'

export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL'

export const USER_LOGOUT = 'USER_LOGOUT'

export const STORE_DATE = 'STORE_DATE'

export const VENDOR_LIST_REQUEST = 'VENDOR_LIST_REQUEST'
export const VENDOR_LIST_SUCCESS = 'VENDOR_LIST_SUCCESS'
export const VENDOR_LIST_FAIL = 'VENDOR_LIST_FAIL'

export const USER_DETAIL_REQUEST = 'USER_DETAIL_REQUEST'
export const USER_DETAIL_SUCCESS = 'USER_DETAIL_SUCCESS'
export const USER_DETAIL_FAIL = 'USER_DETAIL_FAIL'
export const USER_DETAIL_RESET = 'USER_DETAIL_RESET'

export const CUSTOMER_DETAILS_REQUEST = 'CUSTOMER_DETAILS_REQUEST'
export const CUSTOMER_DETAILS_SUCCESS = 'CUSTOMER_DETAILS_SUCCESS'
export const CUSTOMER_DETAILS_FAILURE = 'CUSTOMER_DETAILS_FAILURE'

export const SEAT_LIST_SUCCESS = 'SEAT_LIST_SUCCESS'
export const SEAT_LIST_REQUEST = 'SEAT_LIST_REQUEST'
export const SEAT_LIST_FAIL = 'SEAT_LIST_FAIL'

export const USER_LIST_REQUEST = 'USER_LIST_REQUEST'
export const USER_LIST_SUCCESS = 'USER_LIST_SUCCESS'
export const USER_LIST_FAIL = 'USER_LIST_FAIL'
export const USER_LIST_RESET = 'USER_LIST_RESET'

export const HELP_LIST_REQUEST = 'HELP_LIST_REQUEST'
export const HELP_LIST_CREATE = 'HELP_LIST_CREATE'
export const HELP_LIST_SUCCESS = 'HELP_LIST_SUCCESS'
export const HELP_LIST_FAIL = 'HELP_LIST_FAIL'
export const HELP_LIST_RESET = 'HELP_LIST_RESET'

export const HELP_RESPONSE_REQUEST = 'HELP_RESPONSE_REQUEST'
export const HELP_RESPONSE_SUCCESS = 'HELP_RESPONSE_SUCCESS'
export const HELP_RESPONSE_FAIL = 'HELP_RESPONSE_FAIL'

export const LOCATION_LIST_REQUEST = 'LOCATION_LIST_REQUEST'
export const LOCATION_LIST_SUCCESS = 'LOCATION_LIST_SUCCESS'
export const LOCATION_LIST_FAIL = 'LOCATION_LIST_FAIL'
export const LOCATION_LIST_RESET = 'LOCATION_LIST_RESET'

export const CART_ADD_REQUEST = 'CART_ADD_REQUEST'
export const CART_ADD_SUCCESS = 'CART_ADD_SUCCESS'
export const CART_ADD_FAIL = 'CART_ADD_FAIL'
export const CART_ADD_RESET = 'CART_ADD_RESET'

