export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL'
export const USER_LOGOUT = 'USER_LOGOUT'

export const VENDOR_INFO_REQUEST = 'VENDOR_INFO_REQUEST'
export const VENDOR_INFO_SUCCESS = 'VENDOR_INFO_SUCCESS'
export const VENDOR_INFO_FAIL = 'VENDOR_INFO_FAIL'