export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL'
export const USER_LOGOUT = 'USER_LOGOUT'

export const VENDOR_INFO_REQUEST = 'VENDOR_INFO_REQUEST'
export const VENDOR_INFO_SUCCESS = 'VENDOR_INFO_SUCCESS'
export const VENDOR_INFO_FAIL = 'VENDOR_INFO_FAIL'
export const VENDOR_INFO_RESET = 'VENDOR_INFO_RESET'

export const USER_DETAIL_REQUEST = 'USER_DETAIL_REQUEST'
export const USER_DETAIL_SUCCESS = 'USER_DETAIL_SUCCESS'
export const USER_DETAIL_FAIL = 'USER_DETAIL_FAIL'
export const USER_DETAIL_RESET = 'USER_DETAIL_RESET'

export const USER_UPDATE_REQUEST = 'USER_UPDATE_REQUEST'
export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS'
export const USER_UPDATE_FAIL = 'USER_UPDATE_FAIL'
export const USER_UPDATE_RESET = 'USER_UPDATE_RESET'

export const USER_VENDOR_UPDATE_REQUEST = 'USER_VENDOR_UPDATE_REQUEST'
export const USER_VENDOR_UPDATE_SUCCESS = 'USER_VENDOR_UPDATE_SUCCESS'
export const USER_VENDOR_UPDATE_FAIL = 'USER_VENDOR_UPDATE_FAIL'
export const USER_VENDOR_UPDATE_RESET = 'USER_VENDOR_UPDATE_RESET'
