export const USER_SERVICE_REQUEST = 'USER_SERVICE_REQUEST'
export const USER_SERVICE_SUCCESS = 'USER_SERVICE_SUCCESS'
export const USER_SERVICE_FAIL = 'USER_SERVICE_FAIL'
export const USER_SERVICE_RESET = 'USER_SERVICE_RESET'

export const SERVICE_DELETE_REQUEST = 'SERVICE_DELETE_REQUEST'
export const SERVICE_DELETE_SUCCESS = 'SERVICE_DELETE_SUCCESS'
export const SERVICE_DELETE_FAIL = 'SERVICE_DELETE_FAIL'
export const SERVICE_DELETE_RESET = 'SERVICE_DELETE_RESET'

export const SERVICE_SAVE_REQUEST = 'SERVICE_SAVE_REQUEST'
export const SERVICE_SAVE_SUCCESS = 'SERVICE_SAVE_SUCCESS'
export const SERVICE_SAVE_FAIL = 'SERVICE_SAVE_FAIL'
export const SERVICE_SAVE_RESET = 'SERVICE_SAVE_RESET'


