export const USER_SERVICE_REQUEST = 'USER_SERVICE_REQUEST'
export const USER_SERVICE_SUCCESS = 'USER_SERVICE_SUCCESS'
export const USER_SERVICE_FAIL = 'USER_SERVICE_FAIL'
export const USER_SERVICE_RESET = 'USER_SERVICE_RESET'

export const SERVICE_DELETE_REQUEST = 'SERVICE_DELETE_REQUEST'
export const SERVICE_DELETE_SUCCESS = 'SERVICE_DELETE_SUCCESS'
export const SERVICE_DELETE_FAIL = 'SERVICE_DELETE_FAIL'
export const SERVICE_DELETE_RESET = 'SERVICE_DELETE_RESET'

export const SERVICE_SAVE_REQUEST = 'SERVICE_SAVE_REQUEST'
export const SERVICE_SAVE_SUCCESS = 'SERVICE_SAVE_SUCCESS'
export const SERVICE_SAVE_FAIL = 'SERVICE_SAVE_FAIL'
export const SERVICE_SAVE_RESET = 'SERVICE_SAVE_RESET'

export const SERVICE_DETAIL_REQUEST = 'SERVICE_DETAIL_REQUEST'
export const SERVICE_DETAIL_SUCCESS = 'SERVICE_DETAIL_SUCCESS'
export const SERVICE_DETAIL_FAIL = 'SERVICE_DETAIL_FAIL'
export const SERVICE_DETAIL_RESET = 'SERVICE_DETAIL_RESET'

export const SERVICE_ADD_REQUEST = 'SERVICE_ADD_REQUEST'
export const SERVICE_ADD_SUCCESS = 'SERVICE_ADD_SUCCESS'
export const SERVICE_ADD_FAIL = 'SERVICE_ADD_FAIL'
export const SERVICE_ADD_RESET = 'SERVICE_ADD_RESET'

export const LOCATION_DETAIL_REQUEST = 'LOCATION_DETAIL_REQUEST'
export const LOCATION_DETAIL_SUCCESS = 'LOCATION_DETAIL_SUCCESS'
export const LOCATION_DETAIL_FAIL = 'LOCATION_DETAIL_FAIL'
export const LOCATION_DETAIL_RESET = 'LOCATION_DETAIL_RESET'


