# Generated by Django 3.2.5 on 2021-08-23 12:09

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import etixApp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('userID', models.TextField(default='<function generate_user_id at 0x0000022DBD3113A0>', editable=False, max_length=8, primary_key=True, serialize=False, unique=True)),
                ('username', models.CharField(blank=True, max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('Last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('is_active', models.BooleanField(default=True)),
                ('is_customer', models.BooleanField(default=False)),
                ('is_vendor', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('businessID', models.TextField(default=etixApp.models.generate_business_id, editable=False, max_length=8, primary_key=True, serialize=False, unique=True)),
                ('businessName', models.CharField(max_length=100)),
                ('businessDocument', models.FileField(upload_to='')),
                ('businessBankAcc', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customerID', models.TextField(default=etixApp.models.generate_customer_id, editable=False, max_length=8, primary_key=True, serialize=False, unique=True)),
                ('customerGender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('P', 'Prefer not to say')], max_length=1)),
                ('customerFirstName', models.CharField(blank=True, max_length=100)),
                ('customerLastName', models.CharField(blank=True, max_length=100)),
                ('customerContact_Number', models.TextField(blank=True, max_length=11)),
                ('customerAddress', models.TextField(blank=True, max_length=200)),
                ('customerBirthday', models.DateField()),
                ('created_by', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['customerID'],
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vendorID', models.TextField(default=etixApp.models.generate_vendor_id, editable=False, max_length=8, primary_key=True, serialize=False, unique=True)),
                ('vendorContact_Number', models.TextField(max_length=11)),
                ('vendorStatus', models.BooleanField(default=False)),
                ('created_by', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vendor', to=settings.AUTH_USER_MODEL)),
                ('vendorBusinessDoc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business', to='etixApp.business')),
            ],
            options={
                'ordering': ['vendorID'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ticketID', models.TextField(default=etixApp.models.generate_ticket_id, editable=False, max_length=8, primary_key=True, serialize=False, unique=True)),
                ('ticketName', models.TextField(max_length=100)),
                ('ticketOwn_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket', to='etixApp.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('adminID', models.TextField(default=etixApp.models.generate_admin_id, editable=False, max_length=8, primary_key=True, serialize=False, unique=True)),
                ('created_by', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
