# Generated by Django 3.2.5 on 2021-11-07 05:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import etixApp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('userID', models.TextField(default=etixApp.models.generate_user_id, editable=False, max_length=8, primary_key=True, serialize=False, unique=True)),
                ('username', models.CharField(blank=True, max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('Last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('is_active', models.BooleanField(default=True)),
                ('is_customer', models.BooleanField(default=False)),
                ('is_vendor', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('cartID', models.TextField(default=etixApp.models.generate_cart_id, editable=False, max_length=8, primary_key=True, serialize=False, unique=True)),
                ('cartTotal', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HelpDesk',
            fields=[
                ('helpdeskID', models.TextField(default=etixApp.models.generate_helpdesk_id, editable=False, max_length=8, primary_key=True, serialize=False, unique=True)),
                ('helpdeskTitle', models.TextField(max_length=200, null=True)),
                ('helpdeskMessage', models.TextField(blank=True, max_length=10000, null=True)),
                ('helpdeskDateTime', models.DateTimeField(auto_now_add=True)),
                ('to_vendor', models.BooleanField(default=False)),
                ('to_admin', models.BooleanField(default=False)),
                ('helpdeskStatus', models.CharField(choices=[('OP', 'Open'), ('CL', 'Close'), ('RP', 'Responded')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('locationID', models.TextField(default=etixApp.models.generate_location_id, editable=False, max_length=5, primary_key=True, serialize=False, unique=True)),
                ('locationName', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('seatID', models.TextField(default=etixApp.models.generate_seat_id, editable=False, max_length=8, primary_key=True, serialize=False, unique=True)),
                ('firstQuantity', models.IntegerField(blank=True, null=True)),
                ('businessQuantity', models.IntegerField(blank=True, null=True)),
                ('economyQuantity', models.IntegerField(blank=True, null=True)),
                ('firstPrice', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('businessPrice', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('economyPrice', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('serviceID', models.TextField(default=etixApp.models.generate_service_id, editable=False, max_length=8, primary_key=True, serialize=False, unique=True)),
                ('serviceName', models.TextField(max_length=1000)),
                ('serviceDesc', models.TextField(max_length=10000)),
                ('serviceStatus', models.CharField(choices=[('O', 'Active'), ('X', 'Inactive')], max_length=1)),
                ('serviceTime', models.TimeField(blank=True, null=True)),
                ('serviceFrequency', models.CharField(choices=[('D', 'Daily'), ('W', 'Weekly'), ('M', 'Monthly'), ('O', 'Once')], max_length=7)),
                ('serviceEndDate', models.DateField()),
                ('serviceStartDate', models.DateField()),
                ('servicedepartureTerminal', models.TextField(max_length=1000)),
                ('servicearrivalTerminal', models.TextField(max_length=1000)),
                ('locationFrom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services_location_from', to='etixApp.location')),
                ('locationTo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services_location_to', to='etixApp.location')),
                ('seat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='etixApp.seat')),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vendorID', models.TextField(default=etixApp.models.generate_vendor_id, editable=False, max_length=8, primary_key=True, serialize=False, unique=True)),
                ('vendorContact_Number', models.TextField(max_length=16)),
                ('vendorStatus', models.BooleanField(default=False)),
                ('vendorName', models.CharField(max_length=100)),
                ('vendorBankName', models.CharField(max_length=100)),
                ('vendorBankAcc', models.CharField(max_length=16)),
                ('vendorRegistrationNo', models.CharField(max_length=15)),
                ('created_by', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vendor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['vendorID'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ticketID', models.TextField(default=etixApp.models.generate_ticket_id, editable=False, max_length=8, primary_key=True, serialize=False, unique=True)),
                ('Token', models.TextField(default=etixApp.models.get_token, editable=False, max_length=32, unique=True)),
                ('ownBy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='etixApp.services')),
            ],
        ),
        migrations.AddField(
            model_name='services',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='etixApp.vendor'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('paymentID', models.TextField(default=etixApp.models.generate_payment_id, editable=False, max_length=8, primary_key=True, serialize=False, unique=True)),
                ('paymentStatus', models.CharField(choices=[('UP', 'UnPaid'), ('CP', 'Complete')], max_length=2)),
                ('paymentDateTime', models.DateField(auto_now_add=True)),
                ('cart', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='etixApp.cart')),
            ],
        ),
        migrations.CreateModel(
            name='HelpResponse',
            fields=[
                ('helpResponseID', models.TextField(default=etixApp.models.generate_help_response_id, editable=False, max_length=8, primary_key=True, serialize=False, unique=True)),
                ('helpResponseDateTime', models.DateTimeField(auto_now_add=True)),
                ('helpResponseMessage', models.TextField(blank=True, max_length=10000, null=True)),
                ('helpdesk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='etixApp.helpdesk')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='helpdesk',
            name='receiver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='etixApp.vendor'),
        ),
        migrations.AddField(
            model_name='helpdesk',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customerID', models.TextField(default=etixApp.models.generate_customer_id, editable=False, max_length=8, primary_key=True, serialize=False, unique=True)),
                ('customerGender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('P', 'Prefer not to say')], max_length=1)),
                ('customerFirstName', models.CharField(blank=True, max_length=100)),
                ('customerLastName', models.CharField(blank=True, max_length=100)),
                ('customerContact_Number', models.TextField(blank=True, max_length=16)),
                ('customerAddress', models.TextField(blank=True, max_length=200)),
                ('customerBirthday', models.DateField(blank=True, null=True)),
                ('created_by', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['customerID'],
            },
        ),
        migrations.CreateModel(
            name='CartItems',
            fields=[
                ('cartItemsID', models.TextField(default=etixApp.models.generate_cart_items_id, editable=False, max_length=8, primary_key=True, serialize=False, unique=True)),
                ('seat_Type', models.CharField(choices=[('F', 'First Class'), ('B', 'Business Class'), ('E', 'Economy Class')], max_length=1)),
                ('seat_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cart', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='etixApp.cart')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='etixApp.services')),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('adminID', models.TextField(default=etixApp.models.generate_admin_id, editable=False, max_length=8, primary_key=True, serialize=False, unique=True)),
                ('created_by', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
