# Generated by Django 3.2.5 on 2021-08-25 05:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('etixApp', '0002_auto_20210824_1518'),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpDesk',
            fields=[
                ('helpdeskID', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('helpdeskTitle', models.TextField(max_length=200, null=True)),
                ('helpdeskMessage', models.TextField(blank=True, max_length=10000, null=True)),
                ('helpdeskDateTime', models.DateTimeField(auto_now_add=True)),
                ('helpdeskStatus', models.CharField(choices=[('OP', 'Open'), ('CL', 'Close')], max_length=2)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='etixApp.customer')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='userID',
            field=models.TextField(default='<function generate_user_id at 0x000001D9E2159310>', editable=False, max_length=8, primary_key=True, serialize=False, unique=True),
        ),
        migrations.CreateModel(
            name='HelpResponse',
            fields=[
                ('helpResponseID', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('helpResponseDateTime', models.DateTimeField(auto_now_add=True)),
                ('helpResponseMessage', models.TextField(blank=True, max_length=10000, null=True)),
                ('helpdesk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='etixApp.helpdesk')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
