# Generated by Django 3.2.8 on 2021-10-24 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etixApp', '0002_alter_user_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='servicearrivalTerminal',
            field=models.TextField(default='terminal', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='services',
            name='servicedepartureTerminal',
            field=models.TextField(default='terminal', max_length=1000),
            preserve_default=False,
        ),
    ]
