# Generated by Django 3.2.8 on 2021-11-04 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etixApp', '0002_alter_user_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customerBirthday',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customerGender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('P', 'Prefer not to say')], max_length=1),
        ),
    ]
