# Generated by Django 3.2.8 on 2021-11-04 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etixApp', '0003_auto_20211104_0728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customerBirthday',
            field=models.DateField(blank=True, null=True),
        ),
    ]
