# Generated by Django 3.2.5 on 2021-08-25 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('etixApp', '0003_auto_20210825_1353'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('destinationID', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('destinationTimeDeparture', models.TimeField(blank=True, null=True)),
                ('destinationOnwardDate', models.DateField()),
                ('destinationStartName', models.TextField(max_length=1000)),
                ('destinationEndName', models.TextField(max_length=1000)),
                ('destinationFrom', models.TextField(max_length=1000)),
                ('destinationTo', models.TextField(max_length=1000)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='userID',
            field=models.TextField(default='<function generate_user_id at 0x000002B0D2AD9310>', editable=False, max_length=8, primary_key=True, serialize=False, unique=True),
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('serviceID', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('serviceName', models.TextField(max_length=1000)),
                ('serviceDesc', models.TextField(max_length=10000)),
                ('serviceMedia', models.ImageField(blank=True, null=True, upload_to='')),
                ('serviceStatus', models.CharField(choices=[('AC', 'active'), ('DC', 'Disactive')], max_length=2)),
                ('serviceRowCapacity', models.IntegerField(blank=True, null=True)),
                ('destination', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='etixApp.destination')),
                ('vendor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='etixApp.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('paymentID', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('paymentStatus', models.CharField(choices=[('UP', 'UnPaid'), ('CP', 'Complete')], max_length=2)),
                ('paymentDateTime', models.DateTimeField(auto_now_add=True)),
                ('cart', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='etixApp.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('cartID', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('cartTotal', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='etixApp.customer')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='etixApp.services')),
            ],
        ),
    ]
