# Generated by Django 3.2.8 on 2021-10-24 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etixApp', '0003_auto_20211024_0508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customerContact_Number',
            field=models.TextField(blank=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='vendorContact_Number',
            field=models.TextField(max_length=16),
        ),
    ]
