# Generated by Django 3.2.8 on 2021-10-24 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etixApp', '0004_auto_20211024_0518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='vendorBankAcc',
            field=models.CharField(max_length=16),
        ),
    ]
