# Generated by Django 3.2.5 on 2021-08-25 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etixApp', '0004_auto_20210825_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userID',
            field=models.TextField(default='<function generate_user_id at 0x000001ECD7A1EAF0>', editable=False, max_length=8, primary_key=True, serialize=False, unique=True),
        ),
    ]
