# Generated by Django 3.2.5 on 2021-08-30 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etixApp', '0004_auto_20210830_2124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
    ]
