# Generated by Django 3.2.5 on 2021-10-24 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etixApp', '0005_alter_vendor_vendorbankacc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userID',
            field=models.TextField(default='<function generate_user_id at 0x00000266C50898B0>', editable=False, max_length=8, primary_key=True, serialize=False, unique=True),
        ),
    ]
