# Generated by Django 3.2.5 on 2021-08-25 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etixApp', '0005_alter_user_userid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='serviceMedia',
        ),
        migrations.AlterField(
            model_name='user',
            name='userID',
            field=models.TextField(default='<function generate_user_id at 0x00000270745FEAF0>', editable=False, max_length=8, primary_key=True, serialize=False, unique=True),
        ),
    ]
