# Generated by Django 3.2.5 on 2021-10-24 05:43

from django.db import migrations, models
import etixApp.models


class Migration(migrations.Migration):

    dependencies = [
        ('etixApp', '0006_alter_user_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userID',
            field=models.TextField(default=etixApp.models.generate_user_id, editable=False, max_length=8, primary_key=True, serialize=False, unique=True),
        ),
    ]
