# Generated by Django 3.2.6 on 2021-08-26 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etixApp', '0006_auto_20210826_0437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userID',
            field=models.TextField(default='<function generate_user_id at 0x000001364671F4C0>', editable=False, max_length=8, primary_key=True, serialize=False, unique=True),
        ),
    ]
