# Generated by Django 3.2.5 on 2021-10-27 03:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('etixApp', '0007_alter_user_userid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='helpdesk',
            name='customer',
        ),
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='helpdesk',
            name='to_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='helpdesk',
            name='to_vendor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='helpdesk',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
