# Generated by Django 3.2.5 on 2021-08-30 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etixApp', '0007_alter_user_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
