# Generated by Django 3.2.6 on 2021-08-27 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etixApp', '0008_auto_20210827_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userID',
            field=models.TextField(default='<function generate_user_id at 0x00000264BF9DE4C0>', editable=False, max_length=8, primary_key=True, serialize=False, unique=True),
        ),
    ]
