# Generated by Django 3.2.5 on 2021-10-28 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etixApp', '0009_alter_helpdesk_helpdeskstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userID',
            field=models.TextField(default='<function generate_user_id at 0x000001E4E6C53820>', editable=False, max_length=8, primary_key=True, serialize=False, unique=True),
        ),
    ]
