# Generated by Django 3.2.6 on 2021-08-27 01:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('etixApp', '0009_alter_user_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='row',
            name='destination',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='etixApp.destination'),
        ),
        migrations.AddField(
            model_name='seat',
            name='row',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='etixApp.row'),
        ),
        migrations.AddField(
            model_name='seat',
            name='seatType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='etixApp.seattype'),
        ),
        migrations.AddField(
            model_name='seattype',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='etixApp.services'),
        ),
        migrations.AlterField(
            model_name='user',
            name='userID',
            field=models.TextField(default='<function generate_user_id at 0x000002788ACDE310>', editable=False, max_length=8, primary_key=True, serialize=False, unique=True),
        ),
    ]
