# Generated by Django 3.2.5 on 2021-08-30 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etixApp', '0009_auto_20210830_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
