# Generated by Django 3.2.6 on 2021-08-27 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('etixApp', '0010_auto_20210827_0923'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='seat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='etixApp.seat'),
        ),
        migrations.AlterField(
            model_name='user',
            name='userID',
            field=models.TextField(default='<function generate_user_id at 0x0000019982D9E310>', editable=False, max_length=8, primary_key=True, serialize=False, unique=True),
        ),
    ]
