# Generated by Django 3.2.5 on 2021-08-31 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etixApp', '0011_auto_20210831_0813'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
