# Generated by Django 3.2.6 on 2021-08-27 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etixApp', '0011_auto_20210827_1451'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='vendorBusinessDoc',
        ),
        migrations.AddField(
            model_name='vendor',
            name='vendorBankAcc',
            field=models.CharField(default=121212, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendor',
            name='vendorName',
            field=models.CharField(default='PengeemaVendor', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendor',
            name='vendorRegistrationNo',
            field=models.CharField(default='3232323-T', max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='userID',
            field=models.TextField(default='<function generate_user_id at 0x00000256934AE4C0>', editable=False, max_length=8, primary_key=True, serialize=False, unique=True),
        ),
        migrations.DeleteModel(
            name='Business',
        ),
    ]
