# Generated by Django 3.2.5 on 2021-08-31 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etixApp', '0012_auto_20210831_0840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userID',
            field=models.TextField(default='<function generate_user_id at 0x000002533623FE50>', editable=False, max_length=8, primary_key=True, serialize=False, unique=True),
        ),
    ]
