# Generated by Django 3.2.8 on 2021-10-23 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etixApp', '0014_auto_20210831_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userID',
            field=models.TextField(default='<function generate_user_id at 0x7f779a3cf430>', editable=False, max_length=8, primary_key=True, serialize=False, unique=True),
        ),
    ]
