# Generated by Django 3.2.8 on 2021-10-23 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etixApp', '0015_alter_user_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userID',
            field=models.TextField(default='<function generate_user_id at 0x7ff60ce92310>', editable=False, max_length=8, primary_key=True, serialize=False, unique=True),
        ),
    ]
